name: CI Pipeline

on:
  workflow_dispatch:

env:
  LOCAL_IMAGE_NAME: app:test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force
        
      - name: Delete package-lock.json
        run: rm -f package-lock.json
        
      - name: Install dependencies with package update
        run: npm install

      # Add Trivy scan for npm dependencies
      - name: Run Trivy vulnerability scanner for dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Run unit tests
        run: npm test -- --watchAll=false

      - name: Build the React app
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker image using standard Docker commands
      - name: Build Docker image
        run: |
          docker build -t ${{ env.LOCAL_IMAGE_NAME }} .
          
      # Setup Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.LOCAL_IMAGE_NAME }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'

      # Generate SARIF report
      - name: Run Trivy vulnerability scanner (SARIF report)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true  # Prevents workflow failure while still generating report
        with:
          image-ref: ${{ env.LOCAL_IMAGE_NAME }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          
      # Upload Trivy scan results to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()  # Ensures this runs even if previous steps fail
        with:
          sarif_file: 'trivy-results.sarif'